# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.
import sys

limit = 4000000
def termGenerator():
    for i in range(1, limit):
        yield i

def fib(n):
    return 1 if n in [1, 2] else fib(n-1) + fib(n-2)

sum = 0
termGenObj = termGenerator()

for n in termGenObj:
    fn = fib(n)

    if fn > limit:
        print("limit exceeded at %i" %fn)
        sys.exit()
    else:
        if fn%2 == 0:
            sum += fn

        print("term number is %i" %n)
        print("fibonacci sequence value is %i" %fn)
        print("sum is %i" %sum)
        print("\n")
